_target_: flava.definitions.FLAVAArguments
#pre_init_path: ["/scratch/rc5124/ckpts_mim/last.ckpt", "/ext3/flava_for_pretraining_unified_text_encoder.pt"]
#pre_train_type: ["mim", "mlm"]
training:
  _target_: flava.definitions.TrainingArguments
  lightning:
    max_steps: 25350
    gpus: -1
    val_check_interval: 1014
    num_sanity_val_steps: 0
    strategy: ddp
  lightning_checkpoint:
    dirpath: "/scratch/rc5124/ckpts_vl/"
    filename: flava-{epoch:02d}-{step}
    save_last: true
    every_n_train_steps: 1000
    save_on_train_epoch_end: true
    verbose: true
  lightning_load_from_checkpoint: "/scratch/rc5124/ckpts_vl/last.ckpt"
  seed: 77
  batch_size: 16
  num_workers: 4
  learning_rate: 1e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-6
  warmup_steps: 2000

datasets:
  _target_: flava.definitions.TrainingDatasetsInfo
  selected:
  - image
  - text
  - vl
  image:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.ISICInfo
        csv_path: "/ext3/train_split_metadata.csv"
        img_path: "/ext3/train"
        mode: "image"
    val:
      - _target_: flava.definitions.ISICInfo
        csv_path: "/ext3/val_split_metadata.csv"
        img_path: "/ext3/train"
        mode: "image"
  text:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.ISICInfo
        csv_path: "/ext3/train_split_metadata.csv"
        img_path: "/ext3/train"
        mode: "text"
    val:
      - _target_: flava.definitions.ISICInfo
        csv_path: "/ext3/val_split_metadata.csv"
        img_path: "/ext3/train"
        mode: "text"
  vl:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.ISICInfo
        csv_path: "/ext3/train_split_metadata.csv"
        img_path: "/ext3/train"
        mode: "vl"
    val:
      - _target_: flava.definitions.ISICInfo
        csv_path: "/ext3/val_split_metadata.csv"
        img_path: "/ext3/train"
        mode: "vl"
